### ISSUE TITLE
Manifest dataSources `source` field should not be a list

### ISSUE THREAD

**Issue by cvauclair** [Protean-Labs/graphgen#19]
Each `dataSources` in the generated subgraph manifest (`subgraph.yaml`) should have only one address. Currently, if a `@gg:source` tag specifies multiple entities for a specific interface, only one `dataSources` with multiple `source` fields is created in the manifest. Instead, multiple `dataSources` should be created, each with only one address.

For example, given the following GraphGen tag and interface:
```solidity
/* @gg:source
  name: ERC20
  instances:
    - address: '0x6b175474e89094c44da98b954eedeac495271d0f'
      startBlock: 8928158
      name: DAI
    - address: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48'
      startBlock: 6082465
      name: USDC
*/
interface ERC20 {
  ...
}

```

What is currently generated is in the manifest is:
```yaml
dataSources:
- kind: ethereum/contract
  name: ERC20
  network: mainnet
  source:
  - address: \'0x6b175474e89094c44da98b954eedeac495271d0f\'
    abi: ERC20
    startBlock: 8928158
  - address: \'0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48\'
    abi: ERC20
    startBlock: 6082465
  mapping:
    ...
```

Instead, the following should be generated:
```yaml
dataSources:
- kind: ethereum/contract
  name: DAI
  network: mainnet
  source:
    address: '0x6b175474e89094c44da98b954eedeac495271d0f'
    abi: ERC20
    startBlock: 8928158
  mapping:
    ...
- kind: ethereum/contract
  name: USDC
  network: mainnet
  source:
    address: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48'
    abi: ERC20
    startBlock: 6082465
  mapping:
    ...
```
