### ISSUE TITLE
Subgraph manifest abis filenames are missing `.json`

### ISSUE THREAD

**Issue by cvauclair** [Protean-Labs/graphgen#20]
ABI filenames in the generated subgraph manifest are missing the `.json` file extension, resulting in `File does not exist` errors when running `graph codegen` on the generated subgraph.

Current behavior:
```yaml
dataSources:
- kind: ethereum/contract
  name: Factory
  ...
  mapping:
    ...
    abis:
    - name: Factory
      file: ./abis/IUniswapV2Factory
    - name: Pair
      file: ./abis/IUniswapV2Pair
    ...
```

Expected behavior:
```yaml
dataSources:
- kind: ethereum/contract
  name: Factory
  ...
  mapping:
    ...
    abis:
    - name: Factory
      file: ./abis/IUniswapV2Factory.json
    - name: Pair
      file: ./abis/IUniswapV2Pair.json
    ...
```
