### ISSUE TITLE
Generated manifest `dataSources` have invalid format for the `address` attribute

### ISSUE THREAD

**Issue by cvauclair** [Protean-Labs/graphgen#23]
The generated subgraph manifest does not format addresses correctly. More specifically, addresses should not have backslashes.

Current behavior:
```yaml
dataSources:
- kind: ethereum/contract
  name: Factory
  network: mainnet
  source:
    address: \'0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f\'
    abi: Factory
    startBlock: 10000834
  ...
```

Expected behavior:
```yaml
dataSources:
- kind: ethereum/contract
  name: Factory
  network: mainnet
  source:
    address: '0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f'    # or "0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f"
    abi: Factory
    startBlock: 10000834
  ...
```
