### ISSUE TITLE
Generated manifest event definition do not account for `indexed` types.

### ISSUE THREAD

**Issue by cvauclair** [Protean-Labs/graphgen#24]
The generated subgraph manifest do not account for indexed event fields. 

For instance, given the following interface definition:
```solidity
interface IUniswapV2Factory {
    /* @gg:handler 
      actions:
        - NewSource Pair from pair
    */
    event PairCreated(address indexed token0, address indexed token1, address pair, uint);
    ...
}
```
The currently generated manifest will not include the `indexed` type annotation:
```yaml
dataSources:
- kind: ethereum/contract
  ...
  mapping:
    ...
    eventHandlers:
    - event: PairCreated(address,address,address,uint256)
      handler: handlePairCreated
```

Expected behavior:
```yaml
dataSources:
- kind: ethereum/contract
  ...
  mapping:
    ...
    eventHandlers:
    - event: PairCreated(indexed address,indexed address,address,uint256)
      handler: handlePairCreated
```

Note: The generated ABIs does handle indexed event fields correctly (i.e.: `"indexed": true` is correctly set for indexed event fields).
